package org.lolwat.misc.utils;

import java.util.Arrays;
import java.util.List;

public class ItemUtils {
    public static List<String> SINGULAR_ITEMS = Arrays.asList("Hammer", "Amulet mould", "Bracelet mould", "Ring mould", "Necklace mould");
    public static List<String> EMERGENCY_SELL = Arrays.asList("Adamant arrow",
            "Adamant axe",
            "Adamant full helm",
            "Adamant kiteshield",
            "Adamant pickaxe",
            "Adamant platebody",
            "Adamant platelegs",
            "Adamant plateskirt",
            "Adamant scimitar",
            "Air rune",
            "Amulet of strength",
            "Black ore",
            "Black arrow",
            "Black full helm",
            "Black kiteshield",
            "Black pickaxe",
            "Black platebody",
            "Black platelegs",
            "Black plateskirt",
            "Black scimitar",
            "Blue wizard robe",
            "Big bones",
            "Body rune",
            "Bronze bar",
            "Chaos rune",
            "Clay",
            "Coal",
            "Copper ore",
            "Cowhide",
            "Death rune",
            "Diamond",
            "Diamond amulet (u)",
            "Diamond necklace",
            "Earth rune",
            "Emerald",
            "Emerald amulet (u)",
            "Emerald necklace",
            "Emerald ring",
            "Fire rune",
            "Gold amulet (u)",
            "Gold bar",
            "Gold necklace",
            "Gold ring",
            "Green d'hide chaps",
            "Green d'hide vambraces",
            "Herring",
            "Iron ore",
            "Iron arrow",
            "Iron full helm",
            "Iron kiteshield",
            "Iron pickaxe",
            "Iron platebody",
            "Iron platelegs",
            "Iron plateskirt",
            "Steel scimitar",
            "Leather",
            "Lobster",
            "Logs",
            "Maple shortbow",
            "Mind rune",
            "Mithril arrow",
            "Mithril axe",
            "Mithril bar",
            "Mithril full helm",
            "Mithril kiteshield",
            "Mithril pickaxe",
            "Mithril platebody",
            "Mithril platelegs",
            "Mithril plateskirt",
            "Mithril scimitar",
            "Nature rune",
            "Oak logs",
            "Oak shortbow",
            "Pike",
            "Raw herring",
            "Raw lobster",
            "Raw pike",
            "Raw salmon",
            "Raw sardine",
            "Raw shrimps",
            "Raw trout",
            "Raw tuna",
            "Ruby",
            "Ruby amulet (u)",
            "Ruby necklace",
            "Rune arrow",
            "Rune axe",
            "Rune chainbody",
            "Rune full helm",
            "Rune kiteshield",
            "Rune pickaxe",
            "Rune platelegs",
            "Rune plateskirt",
            "Rune scimitar",
            "Salmon",
            "Sapphire",
            "Sapphire ring",
            "Sardine",
            "Shrimps",
            "Soft clay",
            "Staff of air",
            "Staff of fire",
            "Steel arrow",
            "Steel bar",
            "Steel full helm",
            "Steel kiteshield",
            "Steel pickaxe",
            "Steel platebody",
            "Steel platelegs",
            "Steel plateskirt",
            "Steel scimitar",
            "Tin ore",
            "Trout",
            "Tuna",
            "Uncut diamond",
            "Uncut emerald",
            "Uncut ruby",
            "Uncut sapphire",
            "Water rune",
            "Willow logs",
            "Willow shortbow",
            "Yew logs",
            "Zamarok monk bottom");
}
